### ISSUE TITLE
Framework switch?

### ISSUE THREAD

**Issue by knyazer** [MaximilianYan/Theater-Subtitles#1]
First of all, thanks for the project! The implementation is wonderfully well written, and you certainly poured your heart into it.

However, I would love to see this implemented using some sort of a library: any library to be precise. We are living in the 21st century, after all.

Could you, please, redesign your code using svelte+tailwind? This is a modern but stable choice. Or, if you really hate using node, I can recommend using some sort of jQuery variation: I'm not very experienced but I know there are a ton of them. Even without it, using tailwind would make your life a lot easier I guess.

**Comment by MaximilianYan** [comment]
I can't ((

**Comment by MaximilianYan** [comment]
Also, it is a lightweight app, and so we think, that it would be an overkill

**Comment by knyazer** [comment]
Wow
